// frontend/src/Homepage.tsx
import React, { useEffect, useState } from 'react';

const HomePage = () => {
  const [user, setUser] = useState({});
  useEffect(() => {
    const token = document.cookie.split('; ').find(row => row.startsWith('access_token='))?.split('=')[1] ?? '';
    fetch('http://localhost:3000/users/userInfo', {
      headers: { Authorization: `Bearer ${token}` }})
      .then(response => response.json()).then(data => { setUser(data); })
      .catch(error => console.log(error));
  }, []);

  useEffect(() => {
    if (Object.keys(user).length !== 0) {
      console.log(user);
    }
  }, [user]);

  return (
    <div>Bonjour bienvenue sur la Homepage tu es {user.pseudo}</div>
  );
};

export default HomePage;

// frontend/src/routes/Homepage/+page.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { goto } from "$app/navigation";

    interface User {
        pseudo: string;
        firstName: string;
        lastName: string;
    }

    let user: User;

    const fetchData = async () => {
        const cookies = document.cookie.split(';');
        const accessTokenCookie = cookies.find(cookie => cookie.trim().startsWith('access_token='));
        const accessToken = accessTokenCookie ? accessTokenCookie.split('=')[1] : null;

        if (accessToken) {
            const headers = new Headers();
            headers.append('Authorization', `Bearer ${accessToken}`);

            const response = await fetch('http://localhost:3000/users/userInfo', { headers });
            const data = await response.json();

            user = {
                pseudo: data.pseudo,
                firstName: data.firstname,
                lastName: data.lastname
            };
        } else {
            console.log('Access token not found');
        }
    }

    const gotoRoute = (route: string) => {
        goto(route);
    }

    onMount(() => {
        fetchData();
    });
</script>

<h1>Ceci est la homepage et tu es {user?.firstName}</h1>

<button on:click={() => gotoRoute('/profil')}> Profil </button>
<button on:click={() => gotoRoute('/game')}> Game </button>
<button on:click={() => gotoRoute('/chat')}> Chat </button>
